// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vruagktnzshelswslcgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydWFna3RuenNoZWxzd3NsY2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjA3MTEsImV4cCI6MjA2OTQ5NjcxMX0.IMDBUTXETmNZWXHybribAEifLEccDDt69XdA0AwFYqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});